from django.shortcuts import render
from django.http import HttpResponseRedirect 
from django.http import HttpResponse
from projects.models import Project
from projectgiver.models import ProjectGiver
from FL.models import Freelancer
from bid.models import Bid
from notifications.models import notification
from django.template.context_processors import csrf
from django.contrib.auth.models import User
