# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 13:34
from __future__ import unicode_literals

import FL.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('emailAddress', models.CharField(max_length=250)),
                ('rating', models.DecimalField(blank=True,
                                               decimal_places=2, max_digits=3, null=True)),
                ('profile_image', models.ImageField(
                    blank=True, default='../static/images/index.jpeg', null=True, upload_to=FL.models.get_image_path)),
                ('account', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
