# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='emailAddress',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
