# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectgiver', '__first__'),
        ('FL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=800)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='available', max_length=50)),
                ('noBids', models.IntegerField(default=0)),
                ('deadline', models.DateField()),
                ('freelancerAssigned', models.ForeignKey(blank=True, null=True,
                                                         on_delete=django.db.models.deletion.CASCADE, to='FL.Freelancer')),
                ('proj_poster', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='projectgiver.ProjectGiver')),
            ],
        ),
    ]
