# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='flRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='ppRating',
            field=models.IntegerField(default=0),
        ),
    ]
