# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('FL', '0001_initial'),
        ('projectgiver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('project_status', models.CharField(
                    default='Ongoing', max_length=50)),
                ('freelancer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='FL.Freelancer')),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('project_poster', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='projectgiver.ProjectGiver')),
            ],
        ),
    ]
