# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_seen_stauts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='seen_stauts',
            new_name='seen_status',
        ),
    ]
